#############################################################################
# Makefile for building: qtKeyRec
# Generated by qmake (2.01a) (Qt 4.7.2) on: Thu Oct 6 13:23:54 2011
# Project:  qtKeyRec.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile qtKeyRec.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		qtKeyRec.cpp \
		WiRouter_KeyRec_1.0.5/src/agpf.c \
		WiRouter_KeyRec_1.0.5/src/wirouterkeyrec.c \
		WiRouter_KeyRec_1.0.5/src/telsey.c \
		WiRouter_KeyRec_1.0.5/src/socket.c \
		WiRouter_KeyRec_1.0.5/src/sha256.c \
		WiRouter_KeyRec_1.0.5/src/pirelli.c \
		WiRouter_KeyRec_1.0.5/src/md5.c \
		WiRouter_KeyRec_1.0.5/src/hashword.c moc_qtKeyRec.cpp
OBJECTS       = main.o \
		qtKeyRec.o \
		agpf.o \
		wirouterkeyrec.o \
		telsey.o \
		socket.o \
		sha256.o \
		pirelli.o \
		md5.o \
		hashword.o \
		moc_qtKeyRec.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qtKeyRec.pro
QMAKE_TARGET  = qtKeyRec
DESTDIR       = 
TARGET        = qtKeyRec

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_qtKeyRec.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qtKeyRec.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile qtKeyRec.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile qtKeyRec.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qtKeyRec1.0.0 || $(MKDIR) .tmp/qtKeyRec1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qtKeyRec1.0.0/ && $(COPY_FILE) --parents qtKeyRec.h WiRouter_KeyRec_1.0.5/src/wirouterkeyrec.h WiRouter_KeyRec_1.0.5/src/telsey.h WiRouter_KeyRec_1.0.5/src/socket.h WiRouter_KeyRec_1.0.5/src/sha256.h WiRouter_KeyRec_1.0.5/src/pirelli.h WiRouter_KeyRec_1.0.5/src/md5.h WiRouter_KeyRec_1.0.5/src/hashword.h WiRouter_KeyRec_1.0.5/src/agpf.h .tmp/qtKeyRec1.0.0/ && $(COPY_FILE) --parents main.cpp qtKeyRec.cpp WiRouter_KeyRec_1.0.5/src/agpf.c WiRouter_KeyRec_1.0.5/src/wirouterkeyrec.c WiRouter_KeyRec_1.0.5/src/telsey.c WiRouter_KeyRec_1.0.5/src/socket.c WiRouter_KeyRec_1.0.5/src/sha256.c WiRouter_KeyRec_1.0.5/src/pirelli.c WiRouter_KeyRec_1.0.5/src/md5.c WiRouter_KeyRec_1.0.5/src/hashword.c .tmp/qtKeyRec1.0.0/ && $(COPY_FILE) --parents qtKeyRec.ui .tmp/qtKeyRec1.0.0/ && (cd `dirname .tmp/qtKeyRec1.0.0` && $(TAR) qtKeyRec1.0.0.tar qtKeyRec1.0.0 && $(COMPRESS) qtKeyRec1.0.0.tar) && $(MOVE) `dirname .tmp/qtKeyRec1.0.0`/qtKeyRec1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qtKeyRec1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qtKeyRec.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qtKeyRec.cpp
moc_qtKeyRec.cpp: qtKeyRec.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qtKeyRec.h -o moc_qtKeyRec.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_qtKeyRec.h
compiler_uic_clean:
	-$(DEL_FILE) ui_qtKeyRec.h
ui_qtKeyRec.h: qtKeyRec.ui
	/usr/bin/uic-qt4 qtKeyRec.ui -o ui_qtKeyRec.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp qtKeyRec.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qtKeyRec.o: qtKeyRec.cpp qtKeyRec.h \
		ui_qtKeyRec.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtKeyRec.o qtKeyRec.cpp

agpf.o: WiRouter_KeyRec_1.0.5/src/agpf.c WiRouter_KeyRec_1.0.5/src/agpf.h \
		WiRouter_KeyRec_1.0.5/src/socket.h \
		WiRouter_KeyRec_1.0.5/src/sha256.h \
		WiRouter_KeyRec_1.0.5/src/wirouterkeyrec.h \
		WiRouter_KeyRec_1.0.5/src/telsey.h \
		WiRouter_KeyRec_1.0.5/src/pirelli.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o agpf.o WiRouter_KeyRec_1.0.5/src/agpf.c

wirouterkeyrec.o: WiRouter_KeyRec_1.0.5/src/wirouterkeyrec.c WiRouter_KeyRec_1.0.5/src/wirouterkeyrec.h \
		WiRouter_KeyRec_1.0.5/src/telsey.h \
		WiRouter_KeyRec_1.0.5/src/pirelli.h \
		WiRouter_KeyRec_1.0.5/src/agpf.h \
		WiRouter_KeyRec_1.0.5/src/socket.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o wirouterkeyrec.o WiRouter_KeyRec_1.0.5/src/wirouterkeyrec.c

telsey.o: WiRouter_KeyRec_1.0.5/src/telsey.c WiRouter_KeyRec_1.0.5/src/telsey.h \
		WiRouter_KeyRec_1.0.5/src/hashword.h \
		WiRouter_KeyRec_1.0.5/src/wirouterkeyrec.h \
		WiRouter_KeyRec_1.0.5/src/pirelli.h \
		WiRouter_KeyRec_1.0.5/src/agpf.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o telsey.o WiRouter_KeyRec_1.0.5/src/telsey.c

socket.o: WiRouter_KeyRec_1.0.5/src/socket.c WiRouter_KeyRec_1.0.5/src/socket.h \
		WiRouter_KeyRec_1.0.5/src/wirouterkeyrec.h \
		WiRouter_KeyRec_1.0.5/src/telsey.h \
		WiRouter_KeyRec_1.0.5/src/pirelli.h \
		WiRouter_KeyRec_1.0.5/src/agpf.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o socket.o WiRouter_KeyRec_1.0.5/src/socket.c

sha256.o: WiRouter_KeyRec_1.0.5/src/sha256.c WiRouter_KeyRec_1.0.5/src/sha256.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o sha256.o WiRouter_KeyRec_1.0.5/src/sha256.c

pirelli.o: WiRouter_KeyRec_1.0.5/src/pirelli.c WiRouter_KeyRec_1.0.5/src/md5.h \
		WiRouter_KeyRec_1.0.5/src/pirelli.h \
		WiRouter_KeyRec_1.0.5/src/wirouterkeyrec.h \
		WiRouter_KeyRec_1.0.5/src/telsey.h \
		WiRouter_KeyRec_1.0.5/src/agpf.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pirelli.o WiRouter_KeyRec_1.0.5/src/pirelli.c

md5.o: WiRouter_KeyRec_1.0.5/src/md5.c WiRouter_KeyRec_1.0.5/src/md5.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o md5.o WiRouter_KeyRec_1.0.5/src/md5.c

hashword.o: WiRouter_KeyRec_1.0.5/src/hashword.c WiRouter_KeyRec_1.0.5/src/hashword.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o hashword.o WiRouter_KeyRec_1.0.5/src/hashword.c

moc_qtKeyRec.o: moc_qtKeyRec.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtKeyRec.o moc_qtKeyRec.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

